# Generated by Django 2.0.2 on 2018-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='branch',
            field=models.ManyToManyField(to='main.Branch', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='locomotive',
            name='series',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серия'),
        ),
    ]
