# Generated by Django 2.0.2 on 2018-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180620_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='year',
            field=models.DateField(verbose_name='Год'),
        ),
    ]
