# Generated by Django 2.0.2 on 2018-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180620_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год'),
        ),
    ]
