# Generated by Django 2.0.2 on 2018-06-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180622_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2018, verbose_name='Год')),
            ],
        ),
        migrations.RemoveField(
            model_name='locomotive',
            name='branch',
        ),
        migrations.AddField(
            model_name='run',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Branch', verbose_name='Филиал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='locomotive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Locomotive', verbose_name='Локомотив'),
        ),
        migrations.AlterField(
            model_name='run',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Year', verbose_name='Год'),
        ),
    ]
